name: Build .NET Project

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 * * * *"  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  

      - name: Restaurar dependências
        run: dotnet restore github4women/github4women.csproj

      - name: Compilar o projeto
        run: dotnet build github4women/github4women.csproj --configuration Release --no-restore

      - name: Executar testes (se existirem)
        run: dotnet test github4women/github4women.csproj --no-build --verbosity normal
